# Generated by Django 3.2.3 on 2021-05-29 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Agendamentos Disponíveis',
                'verbose_name_plural': 'Agendamentos Disponíveis',
                'ordering': ['data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite seu nome completo.', max_length=200)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(help_text='Digite seu email.', max_length=254)),
                ('senha', models.CharField(help_text='Digite sua senha.', max_length=50)),
            ],
            options={
                'verbose_name': 'Cidadãos',
                'verbose_name_plural': 'Cidadãos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GruposAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do grupo de atendimento.', max_length=200)),
                ('idade_minima', models.IntegerField(verbose_name='Idade mínima')),
            ],
            options={
                'verbose_name': 'Grupos de Atendimento',
                'verbose_name_plural': 'Grupos de Atendimento',
                'ordering': ['nome', 'idade_minima'],
            },
        ),
        migrations.CreateModel(
            name='LocalVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do local.', max_length=200)),
                ('logradouro', models.CharField(help_text='Digite o logradouro.', max_length=200)),
                ('bairro', models.CharField(help_text='Digite o bairro.', max_length=200)),
                ('cidade', models.CharField(help_text='Digite a cidade.', max_length=200)),
                ('cnes', models.CharField(help_text='Digite o CNES.', max_length=200, verbose_name='CNES')),
            ],
            options={
                'verbose_name': 'Locais de vacinação',
                'verbose_name_plural': 'Locais de vacinação',
                'ordering': ['cidade', 'bairro', 'logradouro', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da sala.', max_length=200)),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.localvacinacao', verbose_name='Local de Vacinação')),
            ],
            options={
                'verbose_name': 'Salas',
                'verbose_name_plural': 'Salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da vacina.', max_length=200)),
                ('fabricante', models.CharField(help_text='Digite o nome do fabricante da vacina.', max_length=200)),
            ],
            options={
                'verbose_name': 'Vacinas',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['nome', 'fabricante'],
            },
        ),
        migrations.CreateModel(
            name='SalasAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vagas', models.IntegerField(verbose_name='Número de vagas')),
                ('id_agendamento_disponivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamentosdisponiveis', verbose_name='Agendamento Disponível')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Agendamentos por Sala',
                'verbose_name_plural': 'Agendamentos por Sala',
                'ordering': ['-numero_vagas'],
            },
        ),
        migrations.AddField(
            model_name='agendamentosdisponiveis',
            name='id_vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.vacina', verbose_name='Vacina'),
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Agendado'), ('c', 'Cancelado'), ('v', 'Vacinado')], help_text='Digite o status do agendamento.', max_length=200, verbose_name='Status do agendamento')),
                ('id_agendamento_disponivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamentosdisponiveis', verbose_name='Agendamento')),
                ('id_cidadao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.cidadao', verbose_name='Nome do Cidadão')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.gruposatendimento', verbose_name='Grupo de Atendimento')),
            ],
            options={
                'verbose_name': 'Agendamentos feitos',
                'verbose_name_plural': 'Agendamentos feitos',
                'ordering': ['status'],
            },
        ),
    ]
