# Generated by Django 3.2.3 on 2024-01-06 19:36

from django.db import migrations
from django.core.management import call_command


def load_command(apps, schema_editor):
    call_command("importar_grupos")


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_command)
    ]
