# Generated by Django 3.2.3 on 2024-01-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_auto_20240106_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentodisponivel',
            name='idade_final',
            field=models.IntegerField(default=0, verbose_name='Idade final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentodisponivel',
            name='idade_inicial',
            field=models.IntegerField(default=0, verbose_name='Idade inicial'),
            preserve_default=False,
        ),
    ]
