# Generated by Django 3.2.3 on 2024-01-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_auto_20240106_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='apto_agendamento',
            field=models.BooleanField(default=False, verbose_name='Está apto para agendamento?'),
        ),
    ]
