# Generated by Django 3.2.3 on 2021-05-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nome', 'email'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
