# Generated by Django 3.2.3 on 2024-01-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_cidadao_apto_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentodisponivel',
            name='horario',
        ),
        migrations.AlterField(
            model_name='agendamentodisponivel',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
