# Generated by Django 3.2.3 on 2021-06-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_auto_20210601_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(choices=[('a', 'Agendado'), ('c', 'Cancelado'), ('v', 'Vacinado')], default='a', help_text='Digite o status do agendamento.', max_length=200, verbose_name='Status do agendamento'),
        ),
    ]
