# Generated by Django 3.2.3 on 2021-06-02 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamentosdisponiveis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='data_realizado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Realizado na data'),
            preserve_default=False,
        ),
    ]
