# Generated by Django 3.2.3 on 2021-06-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamentos_data_realizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='grupo',
        ),
        migrations.AddField(
            model_name='agendamentosdisponiveis',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.gruposatendimento', verbose_name='Grupo de Atendimento'),
            preserve_default=False,
        ),
    ]
